services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: boldare/docker-php-symfony-demo:${VERSION:-0.1.2}
    environment:
      HTTP_API_TESTS_ENTRYPOINT: http://app:8080
